"""add_columns_streetType_streetName

Revision ID: 671106addef2
Revises: 
Create Date: 2025-09-22 09:37:50.988250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
import json
from models import get_database_engine
from import_addresses import fill_street_type_and_name_orm, grouped_to_dict

# revision identifiers, used by Alembic.
revision: str = '671106addef2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('streetName', sa.String(length=300), nullable=True))
    op.add_column('addresses', sa.Column('streetType', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###
    engine = get_database_engine(echo=False)
    abbr_dict = dict()
    with open("grouped_abbrs.json", "r", encoding="utf-8") as f:
        grouped_dict = json.load(f)
        abbr_dict.update(grouped_to_dict(grouped_dict))
    with Session(engine) as session:
        fill_street_type_and_name_orm(session, abbr_dict)
    print("[INFO(my)] streetType и streetName обновлены для всех записей Address.")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'streetType')
    op.drop_column('addresses', 'streetName')
    # ### end Alembic commands ###
